name: Build & Release Shindo Launcher

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      # 1️⃣ Checar repositório
      - uses: actions/checkout@v4

      # 2️⃣ Node
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3️⃣ Rust
      - uses: dtolnay/rust-toolchain@stable

      # 4️⃣ Instalar deps
      - name: Install dependencies
        run: npm install

      # 5️⃣ Build do Tauri
      - name: Build Tauri App
        run: npm run tauri build

      # 6️⃣ Assinar binário
      - name: Sign app for Tauri Updater
        run: |
          FILE_PATH=$(find src-tauri/target/release/bundle -type f \( -name "*.exe" -o -name "*.AppImage" -o -name "*.dmg" \) | head -n 1)
          SIGNATURE=$(npx tauri signer sign --private-key "${{ secrets.TAURI_PRIVATE_KEY }}" --ci --file "$FILE_PATH")
          echo "SIGNATURE=$SIGNATURE" >> $GITHUB_ENV
          echo "FILE_PATH=$FILE_PATH" >> $GITHUB_ENV

      # 7️⃣ Criar latest.json
      - name: Create latest.json
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          cat > latest.json <<JSON
          {
            "version": "${VERSION}",
            "notes": "Nova versão do Shindo Launcher.",
            "pub_date": "${DATE}",
            "platforms": {
              "windows-x86_64": {
                "signature": "${SIGNATURE}",
                "url": "https://github.com/${{ github.repository }}/releases/download/${VERSION}/$(basename "$FILE_PATH")"
              }
            }
          }
          JSON

      # 8️⃣ Upload para release
      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ env.FILE_PATH }}
            latest.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}